## Work with Pandas and Numpy

In [3]:
import numpy as np

In [24]:
zeroD = np.array(4)

In [25]:
zeroD.ndim

0

In [26]:
zeroD

array(4)

A scalar is a zero-dimensional array.

In [27]:
oneD = np.array([1,2,3,4,5])

In [28]:
oneD

array([1, 2, 3, 4, 5])

In [29]:
oneD.ndim

1

In [30]:
oneD[2], oneD[-1]

(3, 5)

### Slicing values

In [31]:
oneD[-3:]

array([3, 4, 5])

In [32]:
oneD[0::2]

array([1, 3, 5])

In [34]:
oneD[0:3:2]

array([1, 3])

In [36]:
list(range(5))

[0, 1, 2, 3, 4]

In [40]:
twoD = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])

In [42]:
twoD.ndim

2

Arrays in the form of $m \times n$ are two dimensional.

In [53]:
twoD[:,0:3:2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13]])

array[row, column]

In [70]:
twoD[1:,1:4:2]

array([[ 7,  9],
       [12, 14]])

In [71]:
np.sum(twoD)

120

In [72]:
np.sum(twoD, axis=0)

array([18, 21, 24, 27, 30])