# Lab 6: Encode & Transform Data

- Columnns represents variables and features.
- $y=f(x)$, where $y$ is the target/dependent variable and $x$ is the independent variable.
- Converting text to numbers is encoding.
- The process of replacing missing values is called **imputation**.

In [104]:
from numpy import array
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [132]:
# y = array(['Positive', 'Negative', 'Negative', 'Positive', 'Positive'])
y = array(['warm','hot','cold','luke warm','hot','cold','warm'])

In [146]:
label_encoder = LabelEncoder()

In [147]:
integer_encoded = label_encoder.fit_transform(y)

In [148]:
integer_encoded

array([3, 1, 0, 2, 1, 0, 3])

In [149]:
df = pd.Series(integer_encoded)

In [150]:
df

0    3
1    1
2    0
3    2
4    1
5    0
6    3
dtype: int64

## One Hot Encoder

In [152]:
from sklearn.preprocessing import OneHotEncoder

In [153]:
one_hot_encoder = OneHotEncoder(sparse_output=False)

In [154]:
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)

In [155]:
integer_encoded

array([[3],
       [1],
       [0],
       [2],
       [1],
       [0],
       [3]])

In [156]:
one_hot_encoded = one_hot_encoder.fit_transform(integer_encoded)

In [157]:
one_hot_encoded

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

One hot encoder removes bias in the integer value used to encode the non-numeric data

[0:] --> First row number and all columns

In [158]:
import numpy as np

In [191]:
label_encoder.inverse_transform([np.argmax(one_hot_encoded[0,:])])[0]

'warm'

In [192]:
label_encoder.inverse_transform([np.argmax(one_hot_encoded[1,:])])[0]

'hot'

In [193]:
label_encoder.inverse_transform([np.argmax(one_hot_encoded[2,:])])[0]

'cold'

In [194]:
label_encoder.inverse_transform([np.argmax(one_hot_encoded[3,:])])[0]

'luke warm'

## Dealing With Missing Data

In [198]:
df = pd.DataFrame({
    'A':[np.nan, 13, 14, 15, 16, np.nan],
    'B':[12, np.nan, 14, 15, 16, np.nan],
    'C':[7, 8, 9, np.nan, 12, np.nan],
})

In [199]:
df

A     B     C
0   NaN  12.0   7.0
1  13.0   NaN   8.0
2  14.0  14.0   9.0
3  15.0  15.0   NaN
4  16.0  16.0  12.0
5   NaN   NaN   NaN

In [201]:
df.dropna(how='all')

A     B     C
0   NaN  12.0   7.0
1  13.0   NaN   8.0
2  14.0  14.0   9.0
3  15.0  15.0   NaN
4  16.0  16.0  12.0

In [202]:
df.dropna(how='any')

A     B     C
2  14.0  14.0   9.0
4  16.0  16.0  12.0

In [203]:
df

A     B     C
0   NaN  12.0   7.0
1  13.0   NaN   8.0
2  14.0  14.0   9.0
3  15.0  15.0   NaN
4  16.0  16.0  12.0
5   NaN   NaN   NaN

In [205]:
df.A.fillna(value=np.mean(df.A))

0    14.5
1    13.0
2    14.0
3    15.0
4    16.0
5    14.5
Name: A, dtype: float64

In [206]:
df

A     B     C
0   NaN  12.0   7.0
1  13.0   NaN   8.0
2  14.0  14.0   9.0
3  15.0  15.0   NaN
4  16.0  16.0  12.0
5   NaN   NaN   NaN

Use `(inplace=True)` to reflect changes into the original dataframe

In [207]:
df

A     B     C
0   NaN  12.0   7.0
1  13.0   NaN   8.0
2  14.0  14.0   9.0
3  15.0  15.0   NaN
4  16.0  16.0  12.0
5   NaN   NaN   NaN

Before encoding categorical data, first impute it.

In [1]:
# I always want to see with numeric missing values

In [211]:
df.fillna(method='ffill')

A     B     C
0   NaN  12.0   7.0
1  13.0  12.0   8.0
2  14.0  14.0   9.0
3  15.0  15.0   9.0
4  16.0  16.0  12.0
5  16.0  16.0  12.0

In [212]:
df.fillna(method='pad')

A     B     C
0   NaN  12.0   7.0
1  13.0  12.0   8.0
2  14.0  14.0   9.0
3  15.0  15.0   9.0
4  16.0  16.0  12.0
5  16.0  16.0  12.0

In [213]:
df.fillna(method='bfill')

A     B     C
0  13.0  12.0   7.0
1  13.0  14.0   8.0
2  14.0  14.0   9.0
3  15.0  15.0  12.0
4  16.0  16.0  12.0
5   NaN   NaN   NaN

In [214]:
from sklearn.impute import SimpleImputer

In [215]:
df

A     B     C
0   NaN  12.0   7.0
1  13.0   NaN   8.0
2  14.0  14.0   9.0
3  15.0  15.0   NaN
4  16.0  16.0  12.0
5   NaN   NaN   NaN

In [217]:
imp = SimpleImputer(strategy='mean')

In [219]:
imp.fit_transform(df) # for dealing with missing numberical values

array([[14.5 , 12.  ,  7.  ],
       [13.  , 14.25,  8.  ],
       [14.  , 14.  ,  9.  ],
       [15.  , 15.  ,  9.  ],
       [16.  , 16.  , 12.  ],
       [14.5 , 14.25,  9.  ]])

1. Separate categorial and numeric.
2. Impute them separately.
3. Combine them

In [1]:
import numpy as np

In [2]:
T = np.linspace(0, 2*np.pi, 25)

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame({
    'x': np.sin(T),
    'x2': np.sin(T),
    'y': 0.5 + np.random.randn(25)
}, index=T)

In [5]:
df

x            x2         y
0.000000  0.000000e+00  0.000000e+00  1.096063
0.261799  2.588190e-01  2.588190e-01 -0.122344
0.523599  5.000000e-01  5.000000e-01  0.567924
0.785398  7.071068e-01  7.071068e-01 -1.011923
1.047198  8.660254e-01  8.660254e-01  2.970182
1.308997  9.659258e-01  9.659258e-01  2.575700
1.570796  1.000000e+00  1.000000e+00  1.960391
1.832596  9.659258e-01  9.659258e-01  2.285963
2.094395  8.660254e-01  8.660254e-01 -1.295913
2.356194  7.071068e-01  7.071068e-01 -0.958900
2.617994  5.000000e-01  5.000000e-01 -1.069516
2.879793  2.588190e-01  2.588190e-01 -0.847381
3.141593  1.224647e-16  1.224647e-16 -0.568274
3.403392 -2.588190e-01 -2.588190e-01  0.600076
3.665191 -5.000000e-01 -5.000000e-01  0.067880
3.926991 -7.071068e-01 -7.071068e-01  0.082391
4.188790 -8.660254e-01 -8.660254e-01  0.528241
4.450590 -9.659258e-01 -9.659258e-01  0.318834
4.712389 -1.000000e+00 -1.000000e+00  1.330465
4.974188 -9.659258e-01 -9.659258e-01 -0.159783
5.235988 -8.660254e-01 -8.660254e-01  0.497368
5.497787 -7.071068e-01 -7.071068e-01  1.339702
5.759587 -5.000000e-01 -5.000000e-01 -0.883546
6.021386 -2.588190e-01 -2.588190e-01  0.263879
6.283185 -2.449294e-16 -2.449294e-16  1.865976

In [6]:
df.iloc[5:12,0] = np.nan

In [7]:
df

x            x2         y
0.000000  0.000000e+00  0.000000e+00  1.096063
0.261799  2.588190e-01  2.588190e-01 -0.122344
0.523599  5.000000e-01  5.000000e-01  0.567924
0.785398  7.071068e-01  7.071068e-01 -1.011923
1.047198  8.660254e-01  8.660254e-01  2.970182
1.308997           NaN  9.659258e-01  2.575700
1.570796           NaN  1.000000e+00  1.960391
1.832596           NaN  9.659258e-01  2.285963
2.094395           NaN  8.660254e-01 -1.295913
2.356194           NaN  7.071068e-01 -0.958900
2.617994           NaN  5.000000e-01 -1.069516
2.879793           NaN  2.588190e-01 -0.847381
3.141593  1.224647e-16  1.224647e-16 -0.568274
3.403392 -2.588190e-01 -2.588190e-01  0.600076
3.665191 -5.000000e-01 -5.000000e-01  0.067880
3.926991 -7.071068e-01 -7.071068e-01  0.082391
4.188790 -8.660254e-01 -8.660254e-01  0.528241
4.450590 -9.659258e-01 -9.659258e-01  0.318834
4.712389 -1.000000e+00 -1.000000e+00  1.330465
4.974188 -9.659258e-01 -9.659258e-01 -0.159783
5.235988 -8.660254e-01 -8.660254e-01  0.497368
5.497787 -7.071068e-01 -7.071068e-01  1.339702
5.759587 -5.000000e-01 -5.000000e-01 -0.883546
6.021386 -2.588190e-01 -2.588190e-01  0.263879
6.283185 -2.449294e-16 -2.449294e-16  1.865976

In [11]:
df.loc[np.pi] = np.nan

In [12]:
df

x            x2         y
0.000000  0.000000e+00  0.000000e+00  1.096063
0.261799  2.588190e-01  2.588190e-01 -0.122344
0.523599  5.000000e-01  5.000000e-01  0.567924
0.785398  7.071068e-01  7.071068e-01 -1.011923
1.047198  8.660254e-01  8.660254e-01  2.970182
1.308997           NaN  9.659258e-01  2.575700
1.570796           NaN  1.000000e+00  1.960391
1.832596           NaN  9.659258e-01  2.285963
2.094395           NaN  8.660254e-01 -1.295913
2.356194           NaN  7.071068e-01 -0.958900
2.617994           NaN  5.000000e-01 -1.069516
2.879793           NaN  2.588190e-01 -0.847381
3.141593           NaN           NaN       NaN
3.403392 -2.588190e-01 -2.588190e-01  0.600076
3.665191 -5.000000e-01 -5.000000e-01  0.067880
3.926991 -7.071068e-01 -7.071068e-01  0.082391
4.188790 -8.660254e-01 -8.660254e-01  0.528241
4.450590 -9.659258e-01 -9.659258e-01  0.318834
4.712389 -1.000000e+00 -1.000000e+00  1.330465
4.974188 -9.659258e-01 -9.659258e-01 -0.159783
5.235988 -8.660254e-01 -8.660254e-01  0.497368
5.497787 -7.071068e-01 -7.071068e-01  1.339702
5.759587 -5.000000e-01 -5.000000e-01 -0.883546
6.021386 -2.588190e-01 -2.588190e-01  0.263879
6.283185 -2.449294e-16 -2.449294e-16  1.865976

In [13]:
df.iloc[::2, -1] = np.nan

In [14]:
df

x            x2         y
0.000000  0.000000e+00  0.000000e+00       NaN
0.261799  2.588190e-01  2.588190e-01 -0.122344
0.523599  5.000000e-01  5.000000e-01       NaN
0.785398  7.071068e-01  7.071068e-01 -1.011923
1.047198  8.660254e-01  8.660254e-01       NaN
1.308997           NaN  9.659258e-01  2.575700
1.570796           NaN  1.000000e+00       NaN
1.832596           NaN  9.659258e-01  2.285963
2.094395           NaN  8.660254e-01       NaN
2.356194           NaN  7.071068e-01 -0.958900
2.617994           NaN  5.000000e-01       NaN
2.879793           NaN  2.588190e-01 -0.847381
3.141593           NaN           NaN       NaN
3.403392 -2.588190e-01 -2.588190e-01  0.600076
3.665191 -5.000000e-01 -5.000000e-01       NaN
3.926991 -7.071068e-01 -7.071068e-01  0.082391
4.188790 -8.660254e-01 -8.660254e-01       NaN
4.450590 -9.659258e-01 -9.659258e-01  0.318834
4.712389 -1.000000e+00 -1.000000e+00       NaN
4.974188 -9.659258e-01 -9.659258e-01 -0.159783
5.235988 -8.660254e-01 -8.660254e-01       NaN
5.497787 -7.071068e-01 -7.071068e-01  1.339702
5.759587 -5.000000e-01 -5.000000e-01       NaN
6.021386 -2.588190e-01 -2.588190e-01  0.263879
6.283185 -2.449294e-16 -2.449294e-16       NaN

Drop rows where all values are missing

In [16]:
df.dropna(how='all', inplace=True)

In [17]:
df

x            x2         y
0.000000  0.000000e+00  0.000000e+00       NaN
0.261799  2.588190e-01  2.588190e-01 -0.122344
0.523599  5.000000e-01  5.000000e-01       NaN
0.785398  7.071068e-01  7.071068e-01 -1.011923
1.047198  8.660254e-01  8.660254e-01       NaN
1.308997           NaN  9.659258e-01  2.575700
1.570796           NaN  1.000000e+00       NaN
1.832596           NaN  9.659258e-01  2.285963
2.094395           NaN  8.660254e-01       NaN
2.356194           NaN  7.071068e-01 -0.958900
2.617994           NaN  5.000000e-01       NaN
2.879793           NaN  2.588190e-01 -0.847381
3.403392 -2.588190e-01 -2.588190e-01  0.600076
3.665191 -5.000000e-01 -5.000000e-01       NaN
3.926991 -7.071068e-01 -7.071068e-01  0.082391
4.188790 -8.660254e-01 -8.660254e-01       NaN
4.450590 -9.659258e-01 -9.659258e-01  0.318834
4.712389 -1.000000e+00 -1.000000e+00       NaN
4.974188 -9.659258e-01 -9.659258e-01 -0.159783
5.235988 -8.660254e-01 -8.660254e-01       NaN
5.497787 -7.071068e-01 -7.071068e-01  1.339702
5.759587 -5.000000e-01 -5.000000e-01       NaN
6.021386 -2.588190e-01 -2.588190e-01  0.263879
6.283185 -2.449294e-16 -2.449294e-16       NaN

In [18]:
from sklearn.impute import SimpleImputer