Take small steps, leave no gaps, everything makes sense. 

In [11]:
"Hello World"

"Hello World"

In [12]:
a_string = "Hello World"

"Hello World"

In [13]:
println(a_string)

Hello World


### What is REPL?

A Read-Eval-Print Loop, or REPL, is a computer environment where user inputs are read and evaluated, and then the results are returned to the user. REPLs provide an interactive environment to explore tools available in specific environments or programming languages. Some examples include the Node.js console, IPython, the Bash shell, and the developer console found in most web browsers. 

In [14]:
println(a_string)
println(a_string)

Hello World
Hello World


In [15]:
print(a_string)
print(a_string)

Hello WorldHello World

In [16]:
# view current working directory
println(pwd())

# change current directory
cd("..")

println(pwd())
cd("Julia")
println(pwd())

/home/hesed/Codes/Jupyter-notes/Julia
/home/hesed/Codes/Jupyter-notes
/home/hesed/Codes/Jupyter-notes/Julia


In [17]:
# strings are added using *
println("Hello " * "World")

Hello World


In [18]:
# strings are repeated using ^
print("Hello " ^ 12)

Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello 

In [19]:
?print

search: print println printstyled sprint isprint prevind parentindices precision



```
print([io::IO], xs...)
```

Write to `io` (or to the default output stream [`stdout`](@ref) if `io` is not given) a canonical (un-decorated) text representation. The representation used by `print` includes minimal formatting and tries to avoid Julia-specific details.

`print` falls back to calling `show`, so most types should just define `show`. Define `print` if your type has a separate "plain" representation. For example, `show` displays strings with quotes, and `print` displays strings without quotes.

See also [`println`](@ref), [`string`](@ref), [`printstyled`](@ref).

# Examples

```jldoctest
julia> print("Hello World!")
Hello World!
julia> io = IOBuffer();

julia> print(io, "Hello", ' ', :World!)

julia> String(take!(io))
"Hello World!"
```


Help can be gotten from the notebook by this syntax:
```Ijulia
?function_name #or keyword
```

In [20]:
a = 1/2
b = 3/4
println(a + b)
println(1/2/3)
println(2/9)

1.25
0.16666666666666666
0.2222222222222222


## Order of Operations in Julia
1. Parenthesis
2. Exponentiation
3. Multiplication and division, from left to right
4. Addition and subtraction, from left to right

> Exponentiation is evaluated from right-to-left in Julia \
> Arithmetic operators have higher precedence than logical operators. \
> Logical operators are evaluated from left to right

In [21]:
println((2^3)^2)
println(2^3^2)

64
512


In [22]:
2/2

1.0

Operation | Symbol
----- | -----
Addition | +
Subtraction | -
Multiplication | *
Exponent | ^
Division | /
Modulus | %
Floor division | `\div`  (÷)
NOT | !
AND | &&
OR | \|\|
Greater than | >
Less than | <
Equal to | ==
Greater than or equal to | >=
Less than or equal to | <=
Not equal to | !=
Bitwise AND | &
Bitwise ORD | \|
Strict comparison operator | === 

In [23]:
# To perform floor division,
# Use ÷
# The character ÷ can be entered by typing \div and pressing Tab.

println(5 ÷ 2)

2


Julia makes use of short-circuit evaluation of logical expressions. This takes advantage of the fact that an expression starting with "false&&" can never be true, and likewise starting with "true||" can never be false.

In [24]:
5040 / 60

84.0

In [25]:
2^2^1^1.3^1.5^1.7^20

4.0

In [26]:
1+3<5 || 2+2<!

true

In [27]:
a = true
b = !!!!a
println(b)

true


In [28]:
3 & 5 > 0

true

In [29]:
8 & 5 > 0

false

## Type System
* Types are formats for storing information. 
* In Julia, only values have types
* 

In [30]:
b = [[1,3,4],[2,3,4]]

2-element Vector{Vector{Int64}}:
 [1, 3, 4]
 [2, 3, 4]

In [31]:
a = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [32]:
typeof(a)

Vector{Int64} (alias for Array{Int64, 1})

In [33]:
typeof(b)

Vector{Vector{Int64}} (alias for Array{Array{Int64, 1}, 1})

In [34]:
# \pm
α = 3
print("γα")

γα

In [35]:
println(α)

3


* Julia follows latex hence characters supported in latex can be used in Julia. E.g. `α` can be obtained by typing `\alpha`
* Emojis can also be used in Julia by using `\:emojiname:`

In [36]:
# setting theta to 0
θ = 0
println(θ)
\:te

0


LoadError: syntax: "\" is not a unary operator

In [37]:
typeof(α)

Int64

In [38]:
😊 = "Something"
println(😊)

Something


In [39]:
typeof(true)

Bool

In [40]:
sizeof(true)

1

In [41]:
println(2 < 1.5)

false


In Julia, where there is a mixture of Int64 and Float64, Int64 gets promoted to Float64 because any integer has a float value, the reverse is not true.

There is a strict comparison operator `===` which takes into consideration the value types before evaluation

In [42]:
2 == 2.0

true

In [43]:
2 === 2.0

false

## Concrete and abstract types
* All the already mentioned types are concrete types. That is, they have no subtypes. 
* Julia defines a supertype for every type (except the type `Any` which is its own supertype).
    * `Int64` has the supertype `Signed`, which has the supertype `Integer`, which has the supertype `Real`.

>  `Real` contains both `Int64` and `Float64`.

* Types with subtypes are called abstract types.
* The most abstract of all is `Any` (Since it is the root of types in Julia).

The actual type of a value in Julia must always be of a concrete type. Why?:
* Some operations change the type of a value by promotion; abstract types help to guide this proccess.
* Functions are written to operate on types. If you write your function to use an abstract type, it will work for all the types underneath that abstract type.

In [44]:
supertypes(Int64)

(Int64, Signed, Integer, Real, Number, Any)

## Variables
* Variables in julia have a name, a value and a type
* A variable name can be almost any string that starts with a letter and continues with letters, numbers or a few other characters.


### Variable Standards
* Avoid the use of capital letters.
* Avoid the use of underscores.
* Avoid the use of exclamation mark. 


### Declaring Arrays
```julia
# Syntax
Array{type}(undef, dimension)
```

In [45]:
a = Array{Float64}(undef, 2, 3)

2×3 Matrix{Float64}:
 6.94628e-310  6.94628e-310  6.94628e-310
 6.94628e-310  6.94628e-310  6.94621e-310

In [46]:
?a

search: a any all abs ans Any axes atan asin asec any! all! acsc acot acos abs2



No documentation found.

`a` is of type `Matrix{Float64}`.

# Summary

```
mutable struct Matrix{Float64}
```

# Supertype Hierarchy

```
Matrix{Float64} <: DenseMatrix{Float64} <: AbstractMatrix{Float64} <: Any
```


In [47]:
?Array

search: Array SubArray BitArray DenseArray StridedArray PermutedDimsArray



```
Array{T,N} <: AbstractArray{T,N}
```

`N`-dimensional dense array with elements of type `T`.

---

```
Array{T}(undef, dims)
Array{T,N}(undef, dims)
```

Construct an uninitialized `N`-dimensional [`Array`](@ref) containing elements of type `T`. `N` can either be supplied explicitly, as in `Array{T,N}(undef, dims)`, or be determined by the length or number of `dims`. `dims` may be a tuple or a series of integer arguments corresponding to the lengths in each dimension. If the rank `N` is supplied explicitly, then it must match the length or number of `dims`. Here [`undef`](@ref) is the [`UndefInitializer`](@ref).

# Examples

```julia-repl
julia> A = Array{Float64, 2}(undef, 2, 3) # N given explicitly
2×3 Matrix{Float64}:
 6.90198e-310  6.90198e-310  6.90198e-310
 6.90198e-310  6.90198e-310  0.0

julia> B = Array{Float64}(undef, 4) # N determined by the input
4-element Vector{Float64}:
   2.360075077e-314
 NaN
   2.2671131793e-314
   2.299821756e-314

julia> similar(B, 2, 4, 1) # use typeof(B), and the given size
2×4×1 Array{Float64, 3}:
[:, :, 1] =
 2.26703e-314  2.26708e-314  0.0           2.80997e-314
 0.0           2.26703e-314  2.26708e-314  0.0
```

---

```
Array{T}(nothing, dims)
Array{T,N}(nothing, dims)
```

Construct an `N`-dimensional [`Array`](@ref) containing elements of type `T`, initialized with [`nothing`](@ref) entries. Element type `T` must be able to hold these values, i.e. `Nothing <: T`.

# Examples

```jldoctest
julia> Array{Union{Nothing, String}}(nothing, 2)
2-element Vector{Union{Nothing, String}}:
 nothing
 nothing

julia> Array{Union{Nothing, Int}}(nothing, 2, 3)
2×3 Matrix{Union{Nothing, Int64}}:
 nothing  nothing  nothing
 nothing  nothing  nothing
```

---

```
Array{T}(missing, dims)
Array{T,N}(missing, dims)
```

Construct an `N`-dimensional [`Array`](@ref) containing elements of type `T`, initialized with [`missing`](@ref) entries. Element type `T` must be able to hold these values, i.e. `Missing <: T`.

# Examples

```jldoctest
julia> Array{Union{Missing, String}}(missing, 2)
2-element Vector{Union{Missing, String}}:
 missing
 missing

julia> Array{Union{Missing, Int}}(missing, 2, 3)
2×3 Matrix{Union{Missing, Int64}}:
 missing  missing  missing
 missing  missing  missing
```


In [48]:
abstypevariable = Array{Integer}(undef, 2,3) # A two-dimensional array with 2 rows and 3 columns

2×3 Matrix{Integer}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [49]:
typeof(abstypevariable)

Matrix{Integer} (alias for Array{Integer, 2})

In [50]:
abstypevariable[2,1]    #NB --- note the brackets, that's how to access elements of an array

LoadError: UndefRefError: access to undefined reference

In [51]:
abstypevariable[1,1] = 1    # Int64 is a subtype of Integer

1

In [52]:
abstypevariable

2×3 Matrix{Integer}:
   1     #undef  #undef
 #undef  #undef  #undef

In [53]:
abstypevariable[1,2] = 5.0  # given value is of type Float64

5.0

In [54]:
abstypevariable

2×3 Matrix{Integer}:
   1       5     #undef
 #undef  #undef  #undef

In [55]:
abstypevariable[2,2] = "stringystringstr"  # strings cannot be converted to any Integer type

LoadError: MethodError: Cannot `convert` an object of type String to an object of type Integer
Closest candidates are:
  convert(::Type{T}, ::T) where T<:Number at ~/julia-1.7.2/share/julia/base/number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at ~/julia-1.7.2/share/julia/base/number.jl:7
  convert(::Type{T}, ::Base.TwicePrecision) where T<:Number at ~/julia-1.7.2/share/julia/base/twiceprecision.jl:262
  ...

In [56]:
some = Array{Float64}([[1,3] [3,4]])

2×2 Matrix{Float64}:
 1.0  3.0
 3.0  4.0

In [57]:
thing = "Hello"

"Hello"

In [58]:
x = Array{Int64}(undef,11, 12)

11×12 Matrix{Int64}:
               4  140594329478928  …               19  140594329482640
 140594329478608                5     140594329482320               22
               3  140594329478992                  20  140594329482704
 140594329478672                6     140594329482384               22
               4  140594329479056                  21  140594329482768
 140594329478736                6  …  140594329482448               23
               3  140594329479120                  21  140594329482832
 140594329478800                5     140594329482512               20
               4  140594329479184                  21  140594329482896
 140594329478864                6     140594329482576                4
               4  140594329479248  …               22  140594329482960

In [59]:
typeof(x)

Matrix{Int64} (alias for Array{Int64, 2})

In [60]:
thing = "Some"::String

"Some"

In [61]:
greeting = "Hello, World"
println(greeting)

Hello, World


In [62]:
a, b, c = 1, 2, 3

(1, 2, 3)

In [63]:
println(a)
println(b)
println(c)

1
2
3


In [64]:
typeof(a)

Int64

In [65]:
?cos

search: cos cosh cosd cosc cospi acos acosh acosd sincos sincosd sincospi const



```
cos(x)
```

Compute cosine of `x`, where `x` is in radians.

See also [`cosd`], [`cospi`], [`sincos`], [`cis`].

---

```
cos(A::AbstractMatrix)
```

Compute the matrix cosine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the cosine. Otherwise, the cosine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> cos(fill(1.0, (2,2)))
2×2 Matrix{Float64}:
  0.291927  -0.708073
 -0.708073   0.291927
```


In [69]:
?help

search: help schedule Channel hasfield @threadcall AbstractChannel



**Welcome to Julia 1.7.2.** The full manual is available at

```
https://docs.julialang.org
```

as well as many great tutorials and learning resources:

```
https://julialang.org/learning/
```

For help on a specific function or macro, type `?` followed by its name, e.g. `?cos`, or `?@time`, and press enter. Type `;` to enter shell mode, `]` to enter package mode.


In [72]:
?exp(3)

```
exp(x)
```

Compute the natural base exponential of `x`, in other words $ℯ^x$.

See also [`exp2`](@ref), [`exp10`](@ref) and [`cis`](@ref).

# Examples

```jldoctest
julia> exp(1.0)
2.718281828459045

julia> exp(im * pi) == cis(pi)
true
```


In [76]:
?binomial

search: binomial



```
binomial(n::Integer, k::Integer)
```

The *binomial coefficient* $\binom{n}{k}$, being the coefficient of the $k$th term in the polynomial expansion of $(1+x)^n$.

If $n$ is non-negative, then it is the number of ways to choose `k` out of `n` items:

$$
\binom{n}{k} = \frac{n!}{k! (n-k)!}
$$

where $n!$ is the [`factorial`](@ref) function.

If $n$ is negative, then it is defined in terms of the identity

$$
\binom{n}{k} = (-1)^k \binom{k-n-1}{k}
$$

See also [`factorial`](@ref).

# Examples

```jldoctest
julia> binomial(5, 3)
10

julia> factorial(5) ÷ (factorial(5-3) * factorial(3))
10

julia> binomial(-5, 3)
-35
```

# External links

  * [Binomial coefficient](https://en.wikipedia.org/wiki/Binomial_coefficient) on Wikipedia.


The binomial coefficient $\binom{n}{k}$, being the coefficient of the $k$th term in the polynomial expansion of $(1+x)^n$.

If $n$ is non-negative, then it is the number of ways to choose k out of n items:

$$ \binom{n}{k} = \frac{n!}{k! (n-k)!} $$

where $n!$ is the factorial function.

If $n$ is negative, then it is defined in terms of the identity

$$ \binom{n}{k} = (-1)^k \binom{k-n-1}{k} $$

In [77]:
?muladd

search: muladd



```
muladd(x, y, z)
```

Combined multiply-add: computes `x*y+z`, but allowing the add and multiply to be merged with each other or with surrounding operations for performance. For example, this may be implemented as an [`fma`](@ref) if the hardware supports it efficiently. The result can be different on different machines and can also be different on the same machine due to constant propagation or other optimizations. See [`fma`](@ref).

# Examples

```jldoctest
julia> muladd(3, 2, 1)
7

julia> 3 * 2 + 1
7
```

---

```
muladd(A, y, z)
```

Combined multiply-add, `A*y .+ z`, for matrix-matrix or matrix-vector multiplication. The result is always the same size as `A*y`, but `z` may be smaller, or a scalar.

!!! compat "Julia 1.6"
    These methods require Julia 1.6 or later.


# Examples

```jldoctest
julia> A=[1.0 2.0; 3.0 4.0]; B=[1.0 1.0; 1.0 1.0]; z=[0, 100];

julia> muladd(A, B, z)
2×2 Matrix{Float64}:
   3.0    3.0
 107.0  107.0
```


In [78]:
muladd(2,3,4)

10

In [79]:
2*3+4

10

In [80]:
cos(1)

0.5403023058681398

In [81]:
methods(muladd)

# 21 methods for generic function "muladd":
[1] muladd(A::Union{LinearAlgebra.Adjoint{var"#s859", <:StridedMatrix{T} where T}, LinearAlgebra.Transpose{var"#s859", <:StridedMatrix{T} where T}, StridedMatrix{var"#s859"}} where var"#s859"<:Number, y::AbstractVector{<:Number}, z::Union{Number, AbstractVector}) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/matmul.jl:238
[2] muladd(A::Union{LinearAlgebra.Adjoint{var"#s859", <:StridedMatrix{T} where T}, LinearAlgebra.Transpose{var"#s859", <:StridedMatrix{T} where T}, StridedMatrix{var"#s859"}} where var"#s859"<:Number, B::Union{LinearAlgebra.Adjoint{var"#s858", <:StridedMatrix{T} where T}, LinearAlgebra.Transpose{var"#s858", <:StridedMatrix{T} where T}, StridedMatrix{var"#s858"}} where var"#s858"<:Number, z::Union{Number, AbstractVecOrMat}) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/matmul.jl:245
[3] muladd(x::LinearAlgebra.Transpose{T, <:AbstractVector} where T, A::AbstractMatrix, z::Union{Number, AbstractVecOrMat}) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/matmul.jl:233
[4] muladd(x::LinearAlgebra.Adjoint{T, <:AbstractVector} where T, A::AbstractMatrix, z::Union{Number, AbstractVecOrMat}) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/matmul.jl:231
[5] muladd(u::AbstractVector, v::Union{LinearAlgebra.Adjoint{T, var"#s859"}, LinearAlgebra.Transpose{T, var"#s859"}} where {T, var"#s859"<:(AbstractVector)}, z::Union{Number, AbstractArray}) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/matmul.jl:218
[6] muladd(z::Complex, w::Complex, x::Complex) in Base at complex.jl:293
[7] muladd(z::Complex, x::Real, y::Real) in Base at complex.jl:337
[8] muladd(z::Complex, x::Real, w::Complex) in Base at complex.jl:338
[9] muladd(z::Complex, w::Complex, x::Real) in Base at complex.jl:341
[10] muladd(x::Real, z::Complex, y::Number) in Base at complex.jl:336
[11] muladd(x::Real, y::Real, z::Complex) in Base at complex.jl:340
[12] muladd(A::LinearAlgebra.UniformScaling, B::LinearAlgebra.UniformScaling, z::LinearAlgebra.UniformScaling) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/uniformscaling.jl:511
[13] muladd(A::LinearAlgebra.Diagonal, B::LinearAlgebra.Diagonal, z::LinearAlgebra.Diagonal) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/diagonal.jl:746
[14] muladd(A::Union{LinearAlgebra.Diagonal, LinearAlgebra.UniformScaling}, B::Union{LinearAlgebra.Diagonal, LinearAlgebra.UniformScaling}, z::Union{LinearAlgebra.Diagonal, LinearAlgebra.UniformScaling}) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/uniformscaling.jl:513
[15] muladd(A::AbstractMatrix, y::AbstractVecOrMat, z::Union{Number, AbstractArray}) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/matmul.jl:204
[16] muladd(x::Float16, y::Float16, z::Float16) in Base at float.jl:410
[17] muladd(x::Float64, y::Float64, z::Float64) in Base at float.jl:412
[18] muladd(x::Float32, y::Float32, z::Float32) in Base at float.jl:411
[19] muladd(x::T, y::T, z::T) where T<:Number in Base at promotion.jl:462
[20] muladd(x::Number, y::Number, z::Number) in Base at promotion.jl:416
[21] muladd(x, y, z) in Base.Math at math.jl:1160

## Defining Functions

In [82]:
myfunc(x) = 20 * x

myfunc (generic function with 1 method)

In [98]:
a = time()
println(myfunc(9))
b = time()
println(b-a)

180
0.0005309581756591797


In [84]:
?time

search: time Timer time_ns timedwait mtime ctime @time @timev @timed istextmime



```
time(t::TmStruct)
```

Converts a `TmStruct` struct to a number of seconds since the epoch.

---

```
time()
```

Get the system time in seconds since the epoch, with fairly high (typically, microsecond) resolution.


In [96]:
a = time()
b = time()
println(b-a)

0.00022602081298828125


In [100]:
addxtoy(x, y) = x + y

addxtoy (generic function with 1 method)

In [108]:
# a = time()
@which addxtoy(33, 23.5)
# b = time()
# println(b-a)

addxtoy(x, y) in Main at In[100]:1

In [107]:
# a = time()
@which 33 + 23.5
# b = time()
# println(b-a)

+(x::Number, y::Number) in Base at promotion.jl:379

In [141]:
function factorialx(x::Int64)
    if x == 1 || x == 0
        return 1
    else
        return x * factorialx(x-1)
    end
end

factorialx (generic function with 2 methods)

In [177]:
a = time()
factorialx(3)
b = time()

print(b-a)

0.00039196014404296875

In [201]:
a = time()
factorial(3)
b = time()

print(b-a)

0.00019693374633789062

In [118]:
?if

search: if ifelse diff notify modifyfield! modifyproperty! elseif symdiff



```
if/elseif/else
```

`if`/`elseif`/`else` performs conditional evaluation, which allows portions of code to be evaluated or not evaluated depending on the value of a boolean expression. Here is the anatomy of the `if`/`elseif`/`else` conditional syntax:

```julia
if x < y
    println("x is less than y")
elseif x > y
    println("x is greater than y")
else
    println("x is equal to y")
end
```

If the condition expression `x < y` is true, then the corresponding block is evaluated; otherwise the condition expression `x > y` is evaluated, and if it is true, the corresponding block is evaluated; if neither expression is true, the `else` block is evaluated. The `elseif` and `else` blocks are optional, and as many `elseif` blocks as desired can be used.

In contrast to some other languages conditions must be of type `Bool`. It does not suffice for conditions to be convertible to `Bool`.

```jldoctest
julia> if 1 end
ERROR: TypeError: non-boolean (Int64) used in boolean context
```


In [131]:
function somew(x)
    if x == 2
        return 1
    end
end

somew (generic function with 1 method)

In [134]:
somew(2)

1

In [140]:
true || false

true

In [202]:
?/

search: / //



```
/(x, y)
```

Right division operator: multiplication of `x` by the inverse of `y` on the right. Gives floating-point results for integer arguments.

# Examples

```jldoctest
julia> 1/2
0.5

julia> 4/2
2.0

julia> 4.5/2
2.25
```


In [203]:
methods(/)

# 111 methods for generic function "/":
[1] /(x::Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}, y::Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}) in Base at int.jl:93
[2] /(x::Union{Integer, Complex{<:Union{Integer, Rational}}}, y::Rational) in Base at rational.jl:345
[3] /(x::Union{Int16, Int32, Int64, Int8, UInt16, UInt32, UInt64, UInt8}, y::BigInt) in Base.GMP at gmp.jl:545
[4] /(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigFloat) in Base.MPFR at mpfr.jl:433
[5] /(c::Union{Int16, Int32, Int64, Int8}, x::BigFloat) in Base.MPFR at mpfr.jl:445
[6] /(c::Union{Float16, Float32, Float64}, x::BigFloat) in Base.MPFR at mpfr.jl:457
[7] /(A::Union{LinearAlgebra.AbstractTriangular, StridedMatrix}, D::LinearAlgebra.Diagonal) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/diagonal.jl:494
[8] /(X::StridedArray{P}, y::P) where P<:Dates.Period in Dates at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/Dates/src/deprecated.jl:44
[9] /(X::StridedArray{P}, y::Real) where P<:Dates.Period in Dates at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/Dates/src/deprecated.jl:44
[10] /(x::Union{SparseArrays.SparseVector{Tv, Ti}, SubArray{Tv, 1, <:SparseArrays.AbstractSparseMatrixCSC{Tv, Ti}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, false}, SubArray{Tv, 1, <:SparseArrays.AbstractSparseVector{Tv, Ti}, Tuple{Base.Slice{Base.OneTo{Int64}}}, false}} where {Tv, Ti}, a::Number) in SparseArrays at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/SparseArrays/src/sparsevector.jl:1476
[11] /(A::LinearAlgebra.Bidiagonal, B::Number) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/bidiag.jl:375
[12] /(A::LinearAlgebra.UnitLowerTriangular, x::Number) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/triangular.jl:871
[13] /(A::LinearAlgebra.UnitLowerTriangular, B::LinearAlgebra.LowerTriangular) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/triangular.jl:1579
[14] /(A::LinearAlgebra.UnitLowerTriangular, B::LinearAlgebra.UnitLowerTriangular) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/triangular.jl:1593
[15] /(x::Rational, y::Union{Integer, Complex{<:Union{Integer, Rational}}, Rational}) in Base at rational.jl:344
[16] /(x::Number, B::BitArray) in Base at bitarray.jl:1201
[17] /(::Number, ::Missing) in Base at missing.jl:124
[18] /(x::Number, v::AbstractVector) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/generic.jl:1154
[19] /(a::R, z::S) where {R<:Real, S<:Complex} in Base at complex.jl:345
[20] /(A::LinearAlgebra.UpperTriangular, x::Number) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/triangular.jl:869
[21] /(A::LinearAlgebra.UpperTriangular, B::LinearAlgebra.UpperTriangular) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/triangular.jl:1600
[22] /(A::LinearAlgebra.UpperTriangular, B::LinearAlgebra.UnitUpperTriangular) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/triangular.jl:1614
[23] /(A::LinearAlgebra.SymTridiagonal, B::Number) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/tridiag.jl:213
[24] /(A::LinearAlgebra.Symmetric, x::Number) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/symmetric.jl:638
[25] /(B::LinearAlgebra.Transpose{T, <:AbstractVector} where T, F::LinearAlgebra.Transpose{<:Any, <:LinearAlgebra.Factorization{<:Real}}) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/factorization.jl:141
[26] /(B::LinearAlgebra.Transpose{T, <:AbstractVector} where T, F::LinearAlgebra.Transpose{<:Any, <:LinearAlgebra.Factorization}) in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/factoriza

In [208]:
60 \ 5040 == 5040 / 60

true

In [206]:
methods(\)

# 135 methods for generic function "\":
[1] \(A::Union{LinearAlgebra.QR{T, S} where S<:AbstractMatrix{T}, LinearAlgebra.QRCompactWY{T, M} where M<:AbstractMatrix{T}, LinearAlgebra.QRPivoted{T, S} where S<:AbstractMatrix{T}}, BIn::Union{Array{Complex{T}, 1}, Array{Complex{T}, 2}}) where T<:Union{Float32, Float64} in LinearAlgebra at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/qr.jl:1016
[2] \(L::Union{LinearAlgebra.Adjoint{T, <:LinearAlgebra.UpperTriangular{T, <:Union{SparseArrays.AbstractSparseMatrixCSC{T, Ti}, SubArray{T, 2, <:SparseArrays.AbstractSparseMatrixCSC{T, Ti}, Tuple{Base.Slice{Base.OneTo{Int64}}, I}} where I<:AbstractUnitRange} where Ti}}, LinearAlgebra.Adjoint{T, <:LinearAlgebra.UnitUpperTriangular{T, <:Union{SparseArrays.AbstractSparseMatrixCSC{T, Ti}, SubArray{T, 2, <:SparseArrays.AbstractSparseMatrixCSC{T, Ti}, Tuple{Base.Slice{Base.OneTo{Int64}}, I}} where I<:AbstractUnitRange} where Ti}}, LinearAlgebra.Adjoint{T, <:LinearAlgebra.LowerTriangular{T, <:Union{SparseArrays.AbstractSparseMatrixCSC{T, Ti}, SubArray{T, 2, <:SparseArrays.AbstractSparseMatrixCSC{T, Ti}, Tuple{Base.Slice{Base.OneTo{Int64}}, I}} where I<:AbstractUnitRange} where Ti}}, LinearAlgebra.Adjoint{T, <:LinearAlgebra.UnitLowerTriangular{T, <:Union{SparseArrays.AbstractSparseMatrixCSC{T, Ti}, SubArray{T, 2, <:SparseArrays.AbstractSparseMatrixCSC{T, Ti}, Tuple{Base.Slice{Base.OneTo{Int64}}, I}} where I<:AbstractUnitRange} where Ti}}, LinearAlgebra.LowerTriangular{T, <:Union{SparseArrays.AbstractSparseMatrixCSC{T, Ti}, SubArray{T, 2, <:SparseArrays.AbstractSparseMatrixCSC{T, Ti}, Tuple{Base.Slice{Base.OneTo{Int64}}, I}} where I<:AbstractUnitRange} where Ti}, LinearAlgebra.Transpose{T, <:LinearAlgebra.UpperTriangular{T, <:Union{SparseArrays.AbstractSparseMatrixCSC{T, Ti}, SubArray{T, 2, <:SparseArrays.AbstractSparseMatrixCSC{T, Ti}, Tuple{Base.Slice{Base.OneTo{Int64}}, I}} where I<:AbstractUnitRange} where Ti}}, LinearAlgebra.Transpose{T, <:LinearAlgebra.UnitUpperTriangular{T, <:Union{SparseArrays.AbstractSparseMatrixCSC{T, Ti}, SubArray{T, 2, <:SparseArrays.AbstractSparseMatrixCSC{T, Ti}, Tuple{Base.Slice{Base.OneTo{Int64}}, I}} where I<:AbstractUnitRange} where Ti}}, LinearAlgebra.Transpose{T, <:LinearAlgebra.LowerTriangular{T, <:Union{SparseArrays.AbstractSparseMatrixCSC{T, Ti}, SubArray{T, 2, <:SparseArrays.AbstractSparseMatrixCSC{T, Ti}, Tuple{Base.Slice{Base.OneTo{Int64}}, I}} where I<:AbstractUnitRange} where Ti}}, LinearAlgebra.Transpose{T, <:LinearAlgebra.UnitLowerTriangular{T, <:Union{SparseArrays.AbstractSparseMatrixCSC{T, Ti}, SubArray{T, 2, <:SparseArrays.AbstractSparseMatrixCSC{T, Ti}, Tuple{Base.Slice{Base.OneTo{Int64}}, I}} where I<:AbstractUnitRange} where Ti}}, LinearAlgebra.UnitLowerTriangular{T, <:Union{SparseArrays.AbstractSparseMatrixCSC{T, Ti}, SubArray{T, 2, <:SparseArrays.AbstractSparseMatrixCSC{T, Ti}, Tuple{Base.Slice{Base.OneTo{Int64}}, I}} where I<:AbstractUnitRange} where Ti}, LinearAlgebra.UnitUpperTriangular{T, <:Union{SparseArrays.AbstractSparseMatrixCSC{T, Ti}, SubArray{T, 2, <:SparseArrays.AbstractSparseMatrixCSC{T, Ti}, Tuple{Base.Slice{Base.OneTo{Int64}}, I}} where I<:AbstractUnitRange} where Ti}, LinearAlgebra.UpperTriangular{T, <:Union{SparseArrays.AbstractSparseMatrixCSC{T, Ti}, SubArray{T, 2, <:SparseArrays.AbstractSparseMatrixCSC{T, Ti}, Tuple{Base.Slice{Base.OneTo{Int64}}, I}} where I<:AbstractUnitRange} where Ti}} where T, B::SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at /home/hesed/julia-1.7.2/share/julia/stdlib/v1.7/SparseArrays/src/linalg.jl:811
[3] \(A::Union{LinearAlgebra.Hermitian{ComplexF64, SparseArrays.SparseMatrixCSC{ComplexF64, Int64}}, LinearAlgebra.Hermitian{Float64, SparseArrays.SparseMatrixCSC{Float64, Int64}}, LinearAlgebra.Symmetric{Float64, SparseArrays.SparseMatrixCSC{Float64, Int64}}}, B::Union{LinearAlgebra.Adjoint{<:Any, <:StridedVecOrMat}, LinearAlgebra.Transpose{<:Any, <:StridedVecOrMat}, StridedVecOrMat}) in SuiteSparse.CHOLMOD at /home/hesed/julia-1

In [207]:
?\

search: \



```
\(x, y)
```

Left division operator: multiplication of `y` by the inverse of `x` on the left. Gives floating-point results for integer arguments.

# Examples

```jldoctest
julia> 3 \ 6
2.0

julia> inv(3) * 6
2.0

julia> A = [4 3; 2 1]; x = [5, 6];

julia> A \ x
2-element Vector{Float64}:
  6.5
 -7.0

julia> inv(A) * x
2-element Vector{Float64}:
  6.5
 -7.0
```

---

```
\(A, B)
```

Matrix division using a polyalgorithm. For input matrices `A` and `B`, the result `X` is such that `A*X == B` when `A` is square. The solver that is used depends upon the structure of `A`.  If `A` is upper or lower triangular (or diagonal), no factorization of `A` is required and the system is solved with either forward or backward substitution. For non-triangular square matrices, an LU factorization is used.

For rectangular `A` the result is the minimum-norm least squares solution computed by a pivoted QR factorization of `A` and a rank estimate of `A` based on the R factor.

When `A` is sparse, a similar polyalgorithm is used. For indefinite matrices, the `LDLt` factorization does not use pivoting during the numerical factorization and therefore the procedure can fail even for invertible matrices.

See also: [`factorize`](@ref), [`pinv`](@ref).

# Examples

```jldoctest
julia> A = [1 0; 1 -2]; B = [32; -4];

julia> X = A \ B
2-element Vector{Float64}:
 32.0
 18.0

julia> A * X == B
true
```

---

```
(\)(F::QRSparse, B::StridedVecOrMat)
```

Solve the least squares problem $\min\|Ax - b\|^2$ or the linear system of equations $Ax=b$ when `F` is the sparse QR factorization of $A$. A basic solution is returned when the problem is underdetermined.

# Examples

```jldoctest
julia> A = sparse([1,2,4], [1,1,1], [1.0,1.0,1.0], 4, 2)
4×2 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
 1.0   ⋅
 1.0   ⋅
  ⋅    ⋅
 1.0   ⋅

julia> qr(A)\fill(1.0, 4)
2-element Vector{Float64}:
 1.0
 0.0
```


In [209]:
addone(x::Int64) = x+1


addone (generic function with 1 method)

In [214]:
addone(ceil(1.2)*10)

LoadError: MethodError: no method matching addone(::Float64)
Closest candidates are:
  addone(::Int64) at In[209]:1

In [216]:
a,b = 1,2
a,b = b, a
println(a, " ", b)

2 1


In [217]:
function test(input)
  println("$input"^2)
end

test(2)

22


In [219]:
"Hello"^3

"HelloHelloHello"

In [221]:
add2(x, y) = return x + y

add2 (generic function with 1 method)

In [222]:
function coordinates(x, y=0, z=0)
  println("($x, $y, $z)")
end

coordinates (generic function with 3 methods)

In [224]:
coordinates(1,0,2)

(1, 0, 2)


In [241]:
(2^3)^2-500

-436

In [232]:
2^2^1^5+2^3

12

In [242]:
println("$(2*6)")

12


In [243]:
typeof("$(2*6)")

String

In [244]:
5 - 7 * 2 + 4

-5

In [246]:
(5-7)*2+4

0

In [247]:
1 + 3 < 5 && 2^2 === 4.0

false

In [251]:
true && ((false && false) || true)

true

In [252]:
?Array

search: Array SubArray BitArray DenseArray StridedArray PermutedDimsArray



```
Array{T,N} <: AbstractArray{T,N}
```

`N`-dimensional dense array with elements of type `T`.

---

```
Array{T}(undef, dims)
Array{T,N}(undef, dims)
```

Construct an uninitialized `N`-dimensional [`Array`](@ref) containing elements of type `T`. `N` can either be supplied explicitly, as in `Array{T,N}(undef, dims)`, or be determined by the length or number of `dims`. `dims` may be a tuple or a series of integer arguments corresponding to the lengths in each dimension. If the rank `N` is supplied explicitly, then it must match the length or number of `dims`. Here [`undef`](@ref) is the [`UndefInitializer`](@ref).

# Examples

```julia-repl
julia> A = Array{Float64, 2}(undef, 2, 3) # N given explicitly
2×3 Matrix{Float64}:
 6.90198e-310  6.90198e-310  6.90198e-310
 6.90198e-310  6.90198e-310  0.0

julia> B = Array{Float64}(undef, 4) # N determined by the input
4-element Vector{Float64}:
   2.360075077e-314
 NaN
   2.2671131793e-314
   2.299821756e-314

julia> similar(B, 2, 4, 1) # use typeof(B), and the given size
2×4×1 Array{Float64, 3}:
[:, :, 1] =
 2.26703e-314  2.26708e-314  0.0           2.80997e-314
 0.0           2.26703e-314  2.26708e-314  0.0
```

---

```
Array{T}(nothing, dims)
Array{T,N}(nothing, dims)
```

Construct an `N`-dimensional [`Array`](@ref) containing elements of type `T`, initialized with [`nothing`](@ref) entries. Element type `T` must be able to hold these values, i.e. `Nothing <: T`.

# Examples

```jldoctest
julia> Array{Union{Nothing, String}}(nothing, 2)
2-element Vector{Union{Nothing, String}}:
 nothing
 nothing

julia> Array{Union{Nothing, Int}}(nothing, 2, 3)
2×3 Matrix{Union{Nothing, Int64}}:
 nothing  nothing  nothing
 nothing  nothing  nothing
```

---

```
Array{T}(missing, dims)
Array{T,N}(missing, dims)
```

Construct an `N`-dimensional [`Array`](@ref) containing elements of type `T`, initialized with [`missing`](@ref) entries. Element type `T` must be able to hold these values, i.e. `Missing <: T`.

# Examples

```jldoctest
julia> Array{Union{Missing, String}}(missing, 2)
2-element Vector{Union{Missing, String}}:
 missing
 missing

julia> Array{Union{Missing, Int}}(missing, 2, 3)
2×3 Matrix{Union{Missing, Int64}}:
 missing  missing  missing
 missing  missing  missing
```


In [256]:
matrix = Array{Float64, 2}(undef, 7, 9)

7×9 Matrix{Float64}:
 1.0e-323   2.0e-322   2.77e-322  …  7.66e-322  8.2e-322   9.0e-322
 4.0e-323   2.08e-322  3.36e-322     7.76e-322  8.3e-322   9.04e-322
 8.4e-323   2.1e-322   3.46e-322     7.8e-322   8.45e-322  9.1e-322
 9.0e-323   2.2e-322   3.5e-322      7.86e-322  8.7e-322   9.2e-322
 1.0e-322   2.4e-322   3.6e-322      7.9e-322   8.8e-322   9.24e-322
 1.24e-322  2.5e-322   3.7e-322   …  8.0e-322   8.84e-322  9.3e-322
 1.33e-322  2.7e-322   3.8e-322      8.05e-322  8.94e-322  2.63563e92

In [257]:
size(matrix)

(7, 9)

In [259]:
print(matrix)

[1.0e-323 2.0e-322 2.77e-322 3.85e-322 5.0e-322 6.27e-322 7.66e-322 8.2e-322 9.0e-322; 4.0e-323 2.08e-322 3.36e-322 3.9e-322 5.5e-322 6.37e-322 7.76e-322 8.3e-322 9.04e-322; 8.4e-323 2.1e-322 3.46e-322 3.95e-322 5.6e-322 6.57e-322 7.8e-322 8.45e-322 9.1e-322; 9.0e-323 2.2e-322 3.5e-322 4.05e-322 5.83e-322 6.6e-322 7.86e-322 8.7e-322 9.2e-322; 1.0e-322 2.4e-322 3.6e-322 4.35e-322 5.93e-322 7.26e-322 7.9e-322 8.8e-322 9.24e-322; 1.24e-322 2.5e-322 3.7e-322 4.74e-322 6.0e-322 7.5e-322 8.0e-322 8.84e-322 9.3e-322; 1.33e-322 2.7e-322 3.8e-322 4.9e-322 6.1e-322 7.6e-322 8.05e-322 8.94e-322 2.635625366112606e92]

In [264]:
println(matrix[:,9])

[9.0e-322, 9.04e-322, 9.1e-322, 9.2e-322, 9.24e-322, 9.3e-322, 2.635625366112606e92]


In [272]:
x = 0
y = 0
if x == 0 && x == y
    print("Hello")
end

Hello

In [273]:
a, b = 2, 3           
function f(x)  
  b = 5 
  a*x + b
end
f(7), b

(19, 3)

In [274]:
function f(x)
  return 2x
  3x
end

f (generic function with 1 method)

In [276]:
f(5)

10